name: Debug Integration Tests

on: [push, pull_request]	

jobs:	
  build:	
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, windows-2019, ubuntu-18.04]
        include: 
        - os: macOS-10.14
          TARGET: macos  
        - os: ubuntu-18.04
          TARGET: linux     
        - os: windows-2019
          TARGET: windows
      # Disable fail-fast; we want results from all OSes even if one fails.
      fail-fast: false

    steps:
    # Set up Flutter and add it to the path.
    - name: Clone Flutter repository with master channel.
      uses: actions/checkout@v2
      with:
        repository: 'flutter/flutter'
        ref: 'master'
        path: 'flutter'
        fetch-depth: 0
    - name: Add Flutter to the PATH for Unix.
      run: echo "::add-path::/$GITHUB_WORKSPACE/flutter/bin"
      if: runner.os != 'Windows'
    - name: Add Flutter to the PATH for Windows.
      run: echo "::add-path::${env:GITHUB_WORKSPACE}\flutter\bin"
      if: runner.os == 'Windows'
    - name: Run Flutter doctor.
      run: flutter doctor -v

    - name: Clone Hydro-SDK.
      uses: actions/checkout@v2
      with:
        path: 'hydro'

    # Run the tests for the repository.
    - name: Get packages for the Flutter project.
      run: flutter pub get
      working-directory: hydro
    # - name: Flutter Analyze
      # run: flutter analyze
      # working-directory: hydro
    # - name: Flutter Format
      # run: flutter format --set-exit-if-changed --dry-run .
      # working-directory: hydro
    - name: Run Flutter unit tests.
      run: flutter test
      working-directory: hydro
